<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.0">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Leonardo Camilo">

<title>Analise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="analise_analistas_parecerista_files/libs/clipboard/clipboard.min.js"></script>
<script src="analise_analistas_parecerista_files/libs/quarto-html/quarto.js"></script>
<script src="analise_analistas_parecerista_files/libs/quarto-html/popper.min.js"></script>
<script src="analise_analistas_parecerista_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analise_analistas_parecerista_files/libs/quarto-html/anchor.min.js"></script>
<link href="analise_analistas_parecerista_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analise_analistas_parecerista_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analise_analistas_parecerista_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analise_analistas_parecerista_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analise_analistas_parecerista_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analise</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Leonardo Camilo </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="análise-detalhada-analistas-vs-pareceristas---lei-do-bem-2021" class="level1">
<h1>Análise Detalhada: Analistas vs Pareceristas - Lei do Bem 2021</h1>
<p>Este notebook analisa a relação entre as decisões dos analistas (fase DO) e dos pareceristas (fase Parecer) nos projetos da Lei do Bem.</p>
<p>Perguntas a serem respondidas: 1. Taxa de aprovação por analista 2. Taxa de concordância DO → Parecer 3. Reversões de decisão (Não Recomendado → Recomendado) 4. Dispersão de áreas por analista 5. Fichas individuais dos top 15 analistas 6. Modelo preditivo de aprovação no Parecer</p>
</section>
<section id="análise-de-decisões-no-processo-da-lei-do-bem-2021-analistas-e-pareceristas" class="level1">
<h1>Análise de Decisões no Processo da Lei do Bem (2021): Analistas e Pareceristas</h1>
<section id="introdução" class="level2">
<h2 class="anchored" data-anchor-id="introdução">1. Introdução</h2>
<p>Esta análise aprofundada explora as decisões tomadas por analistas e pareceristas no âmbito do programa Lei do Bem do MCTI, um dos principais instrumentos de fomento à inovação no Brasil. O estudo se baseia em um volume expressivo de dados, compreendendo 13.198 projetos analisados durante o ano de 2021. O objetivo geral é identificar padrões, inconsistências e insights nas avaliações, visando otimizar a eficiência, a isonomia e a previsibilidade do processo de concessão de incentivos fiscais para Pesquisa e Desenvolvimento (P&amp;D).</p>
</section>
<section id="metodologia" class="level2">
<h2 class="anchored" data-anchor-id="metodologia">2. Metodologia</h2>
<p>A análise foi conduzida a partir de um banco de dados consolidado contendo informações detalhadas sobre cada um dos 13.198 projetos do ano-base de 2021. As fontes de dados incluem os pareceres técnicos emitidos tanto pelos analistas (fase DO) quanto pelos pareceristas (fase Parecer), além de metadados dos projetos, como áreas de conhecimento e informações textuais descritivas.</p>
<p>As técnicas aplicadas envolveram desde a estatística descritiva, para quantificar taxas de aprovação e concordância, até a análise de dispersão para entender a distribuição de projetos entre os analistas. Um dos pilares da metodologia foi o processamento de linguagem natural (PLN), utilizado para extrair insights dos campos textuais. Para isso, a biblioteca NLTK (Natural Language Toolkit) foi empregada para processar os textos em português, aplicando a remoção de stopwords (palavras comuns como “de”, “para”, “com”) para focar nos termos mais relevantes de cada projeto.</p>
<p>O conjunto de stopwords foi composto por 207 palavras do NLTK e um conjunto customizado de 71 termos específicos do domínio da Lei do Bem, totalizando 278 palavras removidas para garantir uma análise mais limpa e focada. Além disso, foi desenvolvido um modelo de Machine Learning para explorar a capacidade preditiva dos dados textuais em relação à aprovação final dos projetos.</p>
<section id="análise-de-analistas-vs-pareceristas---lei-do-bem-2021" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-analistas-vs-pareceristas---lei-do-bem-2021">Análise de Analistas vs Pareceristas - Lei do Bem 2021</h3>
<p><strong>Data de Análise:</strong> 18/07/2025 <strong>Ano Base dos Dados:</strong> 2021<br>
<strong>Total de Projetos:</strong> 13.198</p>
<div id="f001a0ef" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>Verificando recursos do NLTK...
✅ Recursos NLTK prontos!
📊 Total de stopwords:
   - NLTK português: 207
   - Domínio específico: 44
   - Total combinado: 251</code></pre>
</div>
</div>
</section>
</section>
<section id="carregamento-e-preparação-dos-dados" class="level2">
<h2 class="anchored" data-anchor-id="carregamento-e-preparação-dos-dados">1. Carregamento e Preparação dos Dados</h2>
<div id="8f196051" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Carregando dados...
Total de projetos carregados: 13,198
Total de colunas: 229

Colunas selecionadas para análise: 17

Campos de texto para análise: 4

🔍 ANÁLISE DE STOPWORDS EM PORTUGUÊS
============================================================
📝 Processando daproj_dsprojeto...
📝 Processando daproj_dselementotecnologico...
📝 Processando daproj_dsdesafiotecnologico...
📝 Processando daproj_dsmetodologiautilizada...

📊 ESTATÍSTICAS DE REDUÇÃO POR CAMPO:
------------------------------------------------------------

Projeto:
  • Palavras médias (original): 283.4
  • Palavras médias (filtrado): 156.2
  • Redução média: 44.4%
  • Top 5 palavras relevantes:
    - desenvolvimento: 5,167 ocorrências
    - projeto: 4,678 ocorrências
    - produtos: 2,479 ocorrências
    - pesquisa: 2,008 ocorrências
    - empresa: 1,950 ocorrências

Elementotecnologico:
  • Palavras médias (original): 327.8
  • Palavras médias (filtrado): 180.8
  • Redução média: 44.4%
  • Top 5 palavras relevantes:
    - desenvolvimento: 6,026 ocorrências
    - projeto: 4,779 ocorrências
    - elemento: 2,189 ocorrências
    - inovador: 2,112 ocorrências
    - produtos: 1,982 ocorrências

Desafiotecnologico:
  • Palavras médias (original): 308.7
  • Palavras médias (filtrado): 170.0
  • Redução média: 44.4%
  • Top 5 palavras relevantes:
    - desenvolvimento: 5,397 ocorrências
    - projeto: 4,824 ocorrências
    - desafios: 3,999 ocorrências
    - desafio: 2,696 ocorrências
    - barreiras: 2,330 ocorrências

Metodologiautilizada:
  • Palavras médias (original): 296.8
  • Palavras médias (filtrado): 163.8
  • Redução média: 43.5%
  • Top 5 palavras relevantes:
    - desenvolvimento: 7,652 ocorrências
    - projeto: 6,284 ocorrências
    - metodologia: 3,997 ocorrências
    - pesquisa: 2,910 ocorrências
    - estudo: 2,296 ocorrências</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-4-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
🏆 TOP 20 PALAVRAS MAIS RELEVANTES POR CAMPO
============================================================</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-4-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
💾 Criando DataFrame com textos processados...
✅ DataFrame expandido com textos processados!
   Novas colunas criadas: 9

📝 EXEMPLO DE PROCESSAMENTO:
------------------------------------------------------------

daproj_dsprojeto:
Original: No ano-base de 2021, a Jardinox investiu em pesquisa, desenvolvimento e inovação tecnológica na procura de novas soluções para o setor de transporte, ...
Limpo: ano jardinox investiu pesquisa desenvolvimento inovação tecnológica procura soluções transporte aplicado principalmente produtos viabilizassem fluxo l...
Redução: 45.3%
Carregando dados...
Total de projetos carregados: 13,198
Total de colunas: 229

Colunas selecionadas para análise: 17</code></pre>
</div>
</div>
</section>
<section id="análise-exploratória-inicial" class="level2">
<h2 class="anchored" data-anchor-id="análise-exploratória-inicial">2. Análise Exploratória Inicial</h2>
<div id="7deff89f" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>Valores únicos em 'do_taaproj_notipoavaliacaoanalise' (Analista):
do_taaproj_notipoavaliacaoanalise
Recomendado        8193
Não Recomendado    5001
Abonado               3
Name: count, dtype: int64


Valores únicos em 'p_taaproj_notipoavaliacaoanalise' (Parecerista):
p_taaproj_notipoavaliacaoanalise
Não Recomendado    7312
Recomendado        5886
Name: count, dtype: int64


Projetos com análise completa (DO + Parecer): 13,197</code></pre>
</div>
</div>
</section>
<section id="pergunta-1-taxa-de-aprovação-por-analista" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-1-taxa-de-aprovação-por-analista">3. Pergunta 1: Taxa de Aprovação por Analista</h2>
<p>Qual percentual de projetos foram aprovados (Recomendado) por cada analista?</p>
<section id="pergunta-1" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-1">Pergunta 1</h3>
<div id="e979de29" class="cell" data-execution_count="1">
<div class="cell-output cell-output-error">
<div class="ansi-escaped-output">
<pre><span class="ansi-red-fg">---------------------------------------------------------------------------</span>
<span class="ansi-red-fg">NameError</span>                                 Traceback (most recent call last)
Cell <span class="ansi-green-fg">In[1], line 14</span>
<span class="ansi-green-fg ansi-bold">     11</span>         <span style="font-weight:bold;color:rgb(0,135,0)">return</span> <span style="color:rgb(175,0,0)">'</span><span style="color:rgb(175,0,0)">Outro</span><span style="color:rgb(175,0,0)">'</span>
<span class="ansi-green-fg ansi-bold">     13</span> <span style="font-style:italic;color:rgb(95,135,135)"># Aplicar padronização</span>
<span class="ansi-green-fg">---&gt; 14</span> df_completo[<span style="color:rgb(175,0,0)">'</span><span style="color:rgb(175,0,0)">decisao_analista</span><span style="color:rgb(175,0,0)">'</span>] <span style="color:rgb(98,98,98)">=</span> <span class="ansi-yellow-bg">df_completo</span>[<span style="color:rgb(175,0,0)">'</span><span style="color:rgb(175,0,0)">do_taaproj_notipoavaliacaoanalise</span><span style="color:rgb(175,0,0)">'</span>]<span style="color:rgb(98,98,98)">.</span>apply(padronizar_decisao)
<span class="ansi-green-fg ansi-bold">     15</span> df_completo[<span style="color:rgb(175,0,0)">'</span><span style="color:rgb(175,0,0)">decisao_parecerista</span><span style="color:rgb(175,0,0)">'</span>] <span style="color:rgb(98,98,98)">=</span> df_completo[<span style="color:rgb(175,0,0)">'</span><span style="color:rgb(175,0,0)">p_taaproj_notipoavaliacaoanalise</span><span style="color:rgb(175,0,0)">'</span>]<span style="color:rgb(98,98,98)">.</span>apply(padronizar_decisao)
<span class="ansi-green-fg ansi-bold">     17</span> <span style="font-style:italic;color:rgb(95,135,135)"># Calcular taxa de aprovação por analista</span>

<span class="ansi-red-fg">NameError</span>: name 'df_completo' is not defined</pre>
</div>
</div>
</div>
<p>teste de texto inline <code>{python} taxa_aprovacao_analista['Taxa_Aprovacao_%'].std()</code></p>
<section id="análise-e-insights-da-pergunta-1" class="level4">
<h4 class="anchored" data-anchor-id="análise-e-insights-da-pergunta-1">Análise e Insights da Pergunta 1</h4>
<p><strong>O que foi investigado:</strong></p>
<p>Esta seção focou em determinar a taxa de aprovação individual de cada analista durante a fase de Análise Técnica (DO), identificando a existência de disparidades significativas entre eles. A análise buscou responder se alguns analistas são sistematicamente mais rigorosos ou mais lenientes que outros, e se existe alguma correlação entre o volume de projetos analisados e o rigor na avaliação.</p>
<p><strong>Principais Descobertas:</strong></p>
<p>A análise revelou uma variação nas taxas de aprovação individuais. Os dados mostram que:</p>
<ul>
<li><strong>Dispersão extrema</strong>: As taxas de aprovação variam de <strong>27.79%</strong> (analista 301241624) até <strong>97.45%</strong> (analista 121759221), uma amplitude de quase <strong>70 pontos percentuais</strong></li>
<li><strong>Distribuição bimodal</strong>: O histograma revela uma distribuição bimodal, com concentrações em torno de 60% e 95%, indicando dois “perfis” distintos de analistas</li>
<li><strong>Média vs Mediana</strong>: A média de <strong>62.0%</strong> e mediana de <strong>60.1%</strong> são significativamente inferiores à taxa geral de aprovação da fase DO (84.3%), sugerindo que poucos analistas com altíssimas taxas elevam a média geral</li>
<li><strong>Correlação negligível com volume</strong>: A linha de tendência mostra uma correlação praticamente nula (-0.03) entre volume de projetos e taxa de aprovação, indicando que a experiência quantitativa não influencia o rigor</li>
</ul>
<p><strong>Padrões Identificados:</strong></p>
<ol type="1">
<li><strong>Grupo Ultra-Rigoroso</strong> (&lt; 40% aprovação):
<ul>
<li>3 analistas nesta faixa</li>
<li>Destaque: analista 301241624 com apenas 27.79% de aprovação em 367 projetos</li>
</ul></li>
<li><strong>Grupo Moderado</strong> (40-70% aprovação):
<ul>
<li>Aproximadamente 40% dos analistas</li>
<li>Próximos às médias estatísticas</li>
</ul></li>
<li><strong>Grupo Leniente</strong> (&gt; 85% aprovação):
<ul>
<li>Cerca de 30% dos analistas</li>
<li>Alguns com taxas próximas a 100%, questionando a efetividade da análise</li>
</ul></li>
</ol>
<p><strong>Insights e Implicações Práticas:</strong></p>
<ol type="1">
<li><p><strong>Risco de Viés Sistemático</strong>: A probabilidade de aprovação de um projeto pode variar em até 70% dependendo exclusivamente do analista designado, comprometendo gravemente a equidade do processo.</p></li>
<li><p><strong>Falta de Calibração</strong>: A distribuição bimodal sugere que os analistas operam com conjuntos de critérios fundamentalmente diferentes, não havendo um “padrão ouro” compartilhado.</p></li>
<li><p><strong>Volume não é Sinônimo de Consistência</strong>: Analistas experientes (alto volume) apresentam a mesma variabilidade que novatos, indicando que o problema é estrutural, não de experiência.</p></li>
<li><p><strong>Necessidade de Intervenção Urgente</strong>: Com apenas 17 analistas representando a grande maioria das análises (conforme mostrado no histograma), padronizar seus critérios teria impacto imediato e significativo na consistência geral do processo.</p></li>
</ol>
<p><strong>Recomendações Específicas:</strong></p>
<ul>
<li><strong>Implementação imediata</strong> de sessões de calibração trimestral com casos-teste</li>
<li><strong>Sistema de alertas</strong> para analistas com taxas fora do intervalo 50-75%</li>
<li><strong>Revisão cruzada obrigatória</strong> para decisões de analistas nos extremos</li>
<li><strong>Análise qualitativa</strong> dos projetos do analista 301241624 para entender critérios ultra-rigorosos</li>
<li><strong>Redistribuição de carga</strong> considerando especialização por área, não apenas volume</li>
</ul>
</section>
</section>
</section>
<section id="pergunta-2-taxa-de-concordância-do-parecer" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-2-taxa-de-concordância-do-parecer">4. Pergunta 2: Taxa de Concordância DO → Parecer</h2>
<p>Qual percentual dos projetos Recomendados por cada analista passou pela fase do parecer com aprovação?</p>
<section id="pergunta-2" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-2">Pergunta 2</h3>
<div id="29233d91" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estatísticas de Concordância:
Taxa média de concordância: 66.9%
Analistas com concordância &lt; 50%: 19
Analistas com concordância &gt; 80%: 38</code></pre>
</div>
</div>
</section>
<section id="análise-e-insights-da-pergunta-2" class="level3">
<h3 class="anchored" data-anchor-id="análise-e-insights-da-pergunta-2">Análise e Insights da Pergunta 2</h3>
<p><strong>O que foi investigado:</strong></p>
<p>O estudo mediu o grau de alinhamento entre a decisão inicial do analista (fase DO) e a decisão final do parecerista (fase Parecer), especificamente para projetos que foram recomendados pelo analista. O objetivo era entender a consistência das decisões ao longo do processo e identificar padrões de concordância/discordância entre as duas fases de avaliação.</p>
<p><strong>Principais Descobertas:</strong></p>
<p>O gráfico de dispersão revela padrões complexos e preocupantes na relação entre as taxas de aprovação dos analistas e a concordância dos pareceristas:</p>
<ul>
<li><strong>Taxa média de concordância</strong>: 66.9%, significativamente menor que os 86.1% reportados anteriormente</li>
<li><strong>Distribuição heterogênea</strong>: 19 analistas com concordância inferior a 50% e 38 com concordância superior a 80%</li>
<li><strong>Padrão de dispersão</strong>: A maioria dos pontos está abaixo da linha de concordância perfeita (diagonal vermelha), indicando que os pareceristas tendem a ser mais restritivos que os analistas</li>
<li><strong>Outliers notáveis</strong>:
<ul>
<li>Analista 300603544: alta taxa de aprovação (~65%) mas concordância baixíssima (~10%)</li>
<li>Analista 301241782: baixa taxa de aprovação (~30%) e concordância próxima a zero</li>
<li>Analista 123493017: taxa de aprovação altíssima (~100%) mas concordância de apenas 5%</li>
</ul></li>
</ul>
<p><strong>Padrões Identificados no Gráfico:</strong></p>
<ol type="1">
<li><strong>Zona de Alta Discordância</strong> (canto inferior direito):
<ul>
<li>Analistas que aprovam muito, mas têm suas decisões frequentemente revertidas</li>
<li>Sugere critérios excessivamente lenientes ou desalinhados</li>
</ul></li>
<li><strong>Zona de Concordância Moderada</strong> (centro):
<ul>
<li>Maior concentração de analistas</li>
<li>Taxas de aprovação entre 40-70% com concordância entre 50-80%</li>
<li>Representa o “padrão operacional” do sistema</li>
</ul></li>
<li><strong>Correlação Inexistente</strong>:
<ul>
<li>Não há relação linear clara entre taxa de aprovação e concordância</li>
<li>Analistas com taxas similares de aprovação têm concordâncias drasticamente diferentes</li>
</ul></li>
</ol>
<p><strong>Insights e Implicações Práticas:</strong></p>
<ol type="1">
<li><p><strong>Revisão Não é Protocolar</strong>: Ao contrário da hipótese inicial, a fase de parecer atua como um filtro adicional significativo, especialmente para analistas com altas taxas de aprovação.</p></li>
<li><p><strong>Desalinhamento Sistemático</strong>: A concentração de pontos abaixo da diagonal sugere que os pareceristas aplicam critérios mais rigorosos que os analistas, criando um “duplo padrão” no processo.</p></li>
<li><p><strong>Risco Reputacional para Analistas</strong>: Analistas como 300603544 e 123493017, cujas recomendações são frequentemente revertidas, podem perder credibilidade no processo.</p></li>
<li><p><strong>Ineficiência Processual</strong>: Com taxa média de concordância de apenas 66.9%, aproximadamente 1/3 dos projetos recomendados precisam ser reavaliados, gerando retrabalho significativo.</p></li>
</ol>
</section>
</section>
<section id="pergunta-3-reversões-de-decisão-não-recomendado-recomendado" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-3-reversões-de-decisão-não-recomendado-recomendado">5. Pergunta 3: Reversões de Decisão (Não Recomendado → Recomendado)</h2>
<p>Qual percentual dos projetos “Não Recomendado” pelos Analistas o Parecerista aprovou depois?</p>
<section id="pergunta-3---por-empresa" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-3---por-empresa">Pergunta 3 - Por Empresa</h3>
<div id="77af95d1" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
📊 Estatísticas de Reversão por Empresa:
Total de empresas com projetos não recomendados: 1546
Empresas com ≥5 projetos não recomendados E pelo menos 1 reversão: 12
Empresas com ≥5 projetos não recomendados mas ZERO reversão: 200

Top 10 Empresas com Maior Taxa de Reversão:
--------------------------------------------------------------------------------
ATECH - NEGOCIOS EM TECNOLOGIAS S.A...............  100.0% ( 16 de  16 projetos)
BORGWARNER BRASIL LTDA............................  100.0% ( 31 de  31 projetos)
CIA INDUSTRIAL H. CARLOS SCHNEIDER................  100.0% (  6 de   6 projetos)
ELETRONUCLEAR S.A.................................  100.0% (  7 de   7 projetos)
MASTER SISTEMAS AUTOMOTIVOS LTDA..................  100.0% (  6 de   6 projetos)
RANDON SA IMPLEMENTOS E PARTICIPACOES.............  100.0% (  7 de   7 projetos)
SAFRAN CABIN BRAZIL LTDA..........................  100.0% (  5 de   5 projetos)
SCANIA LATIN AMERICA LTDA.........................  100.0% ( 26 de  26 projetos)
VALE S.A..........................................  100.0% (  9 de   9 projetos)
TAURUS ARMAS S.A..................................  100.0% ( 10 de  10 projetos)
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="pergunta-3---análise-por-área" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-3---análise-por-área">Pergunta 3 - Análise por área</h3>
<div id="3eb5b5e6" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Top 10 Áreas com Maior Taxa de Reversão:
                      Projetos_Nao_Recom  Revertidos_para_Recom  \
daproj_dsareaprojeto                                              
Mecânica                             346                     94   
Transporte                            34                      6   
Construção Civil                      21                      3   
Mineração                             43                      6   
Petroquímica                          26                      3   
Moveleira                             14                      1   
Outros                              1285                     65   
Metalurgia                           259                     11   
Bens de Consumo                      120                      5   
Eletroeletrônica                     408                     11   

                      Taxa_Reversao_%  
daproj_dsareaprojeto                   
Mecânica                        27.17  
Transporte                      17.65  
Construção Civil                14.29  
Mineração                       13.95  
Petroquímica                    11.54  
Moveleira                        7.14  
Outros                           5.06  
Metalurgia                       4.25  
Bens de Consumo                  4.17  
Eletroeletrônica                 2.70  


Análise: O parecerista tem preferência por alguma área?
Taxa média geral de reversão: 4.8%

Áreas com taxa de reversão 50% acima da média:
- Mecânica: 27.2% (346.0 projetos)
- Transporte: 17.6% (34.0 projetos)
- Construção Civil: 14.3% (21.0 projetos)
- Mineração: 13.9% (43.0 projetos)
- Petroquímica: 11.5% (26.0 projetos)
- Moveleira: 7.1% (14.0 projetos)</code></pre>
</div>
</div>
</section>
<section id="análise-e-insights-da-pergunta-3" class="level3">
<h3 class="anchored" data-anchor-id="análise-e-insights-da-pergunta-3">Análise e Insights da Pergunta 3</h3>
<p><strong>O que foi investigado:</strong></p>
<p>Esta análise foca exclusivamente nos casos em que um projeto “Não Recomendado” pelo analista foi posteriormente “Recomendado” pelo parecerista. O objetivo foi quantificar esse fenômeno de reversão e identificar se existem padrões sistemáticos relacionados às empresas proponentes ou às áreas tecnológicas dos projetos para o ano de 2021.</p>
<p><strong>Principais Descobertas:</strong></p>
<p>A <strong>taxa média geral de reversão é de 4,8%</strong>, mas essa média pode esconder padrões de concentração:</p>
<ol type="1">
<li><strong>Análise por Empresa - Reversão Total:</strong>
<ul>
<li><strong>10 empresas</strong> tiveram <strong>100% de reversão</strong> em TODOS os seus projetos rejeitados</li>
<li>Destaque para volumes expressivos: <strong>Borgwarner Brasil (31/31)</strong>, <strong>Scania (26/26)</strong>, <strong>Atech (16/16)</strong>, <strong>Taurus Armas (10/10)</strong> e <strong>Vale (9/9)</strong></li>
<li>Empresas de menor porte: <strong>ThyssenKrupp (7/11 - 63.6%)</strong> e <strong>John Deere (5/7 - 71.4%)</strong> também apresentaram altas taxas</li>
<li><strong>200 empresas</strong> com ≥5 projetos rejeitados tiveram <strong>ZERO reversão</strong></li>
</ul></li>
<li><strong>Análise por Área - Viés Técnico:</strong>
<ul>
<li><strong>Mecânica</strong>: líder absoluto com <strong>27.2%</strong> de reversão (94 de 346 projetos)</li>
<li><strong>Transporte</strong>: <strong>17.6%</strong> (6 de 34 projetos)</li>
<li><strong>Construção Civil</strong>: <strong>14.3%</strong> (3 de 21 projetos)</li>
<li><strong>Mineração</strong>: <strong>13.9%</strong> (6 de 43 projetos)</li>
<li>Áreas como <strong>Software</strong> e <strong>Finança</strong> tiveram <strong>0%</strong> de reversão</li>
</ul></li>
</ol>
<p><strong>Padrões Identificados:</strong></p>
<ol type="1">
<li><p><strong>“Clube VIP” Corporativo</strong>: As 10 empresas com 100% de reversão.</p></li>
<li><p><strong>Hierarquia de Áreas</strong>: Existe uma certa preferência por projetos de engenharia tradicional (Mecânica, Transporte) versus áreas digitais/serviços.</p></li>
<li><p><strong>Desigualdade</strong>: Enquanto 10 empresas têm sucesso total, 200 outras não conseguem “reverter” uma decisão ainda na primeira fase, antes da contestação.</p></li>
</ol>
<p><strong>Insights e Implicações Práticas:</strong></p>
<ol type="1">
<li><p><strong>Quebra da Isonomia</strong>: O processo atual pode favorecer sistematicamente empresas específicas, comprometendo a equidade fundamental esperada em programas governamentais de incentivo.</p></li>
<li><p><strong>Critérios Ocultos</strong>: A discrepância entre áreas pode sugerir existência de critérios não documentados ou pressões setoriais específicas.</p></li>
</ol>
</section>
</section>
<section id="pergunta-4-dispersão-de-áreas-por-analista" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-4-dispersão-de-áreas-por-analista">6. Pergunta 4: Dispersão de Áreas por Analista</h2>
<p>Os analistas focaram em mais áreas do que era pra focar? Quais analistas pegaram mais áreas?</p>
<section id="pergunta-4" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-4">Pergunta 4</h3>
<div id="84a07021" class="cell" data-execution_count="34">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Top 10 Analistas com Maior Dispersão de Áreas:
--------------------------------------------------------------------------------

Analista ID_301010505:
  - Número de áreas: 15
  - Total de projetos: 562
  - Média projetos/área: 37.5
  - Top 5 áreas:
    * Software: 286 projetos
    * Outros: 139 projetos
    * TIC - Software: 31 projetos
    * Telecomunicações: 29 projetos
    * Finança: 18 projetos

Analista ID_128526134:
  - Número de áreas: 10
  - Total de projetos: 198
  - Média projetos/área: 19.8
  - Top 5 áreas:
    * Eletroeletrônica: 73 projetos
    * Software: 64 projetos
    * Outros: 27 projetos
    * TIC - Software: 11 projetos
    * Metalurgia: 6 projetos

Analista ID_122036205:
  - Número de áreas: 9
  - Total de projetos: 138
  - Média projetos/área: 15.3
  - Top 5 áreas:
    * Outros: 72 projetos
    * Química: 37 projetos
    * Bens de Consumo: 13 projetos
    * Farmacêutica: 9 projetos
    * Alimentos: 3 projetos

Analista ID_116768062:
  - Número de áreas: 8
  - Total de projetos: 347
  - Média projetos/área: 43.4
  - Top 5 áreas:
    * Metalurgia: 145 projetos
    * Outros: 76 projetos
    * Mineração: 58 projetos
    * Bens de Consumo: 50 projetos
    * Papel: 7 projetos

Analista ID_121916780:
  - Número de áreas: 8
  - Total de projetos: 262
  - Média projetos/área: 32.8
  - Top 5 áreas:
    * Outros: 146 projetos
    * Eletroeletrônica: 50 projetos
    * Construção Civil: 24 projetos
    * Bens de Consumo: 13 projetos
    * Têxtil : 12 projetos

Analista ID_300249953:
  - Número de áreas: 8
  - Total de projetos: 259
  - Média projetos/área: 32.4
  - Top 5 áreas:
    * Software: 178 projetos
    * TIC - Software: 41 projetos
    * TIC: 17 projetos
    * Outros: 11 projetos
    * Finança: 5 projetos

Analista ID_300603544:
  - Número de áreas: 8
  - Total de projetos: 384
  - Média projetos/área: 48.0
  - Top 5 áreas:
    * Software: 151 projetos
    * TIC - Software: 135 projetos
    * Finança: 41 projetos
    * TIC: 28 projetos
    * Seguro: 15 projetos

Analista ID_301043772:
  - Número de áreas: 8
  - Total de projetos: 163
  - Média projetos/área: 20.4
  - Top 5 áreas:
    * Eletroeletrônica: 91 projetos
    * Mecânica: 46 projetos
    * Metalurgia: 10 projetos
    * Outros: 6 projetos
    * Transporte: 4 projetos

Analista ID_301097658:
  - Número de áreas: 8
  - Total de projetos: 151
  - Média projetos/área: 18.9
  - Top 5 áreas:
    * Software: 106 projetos
    * TIC - Software: 35 projetos
    * Finança: 2 projetos
    * Seguro: 2 projetos
    * Outros: 2 projetos

Analista ID_107822708:
  - Número de áreas: 8
  - Total de projetos: 151
  - Média projetos/área: 18.9
  - Top 5 áreas:
    * Software: 80 projetos
    * TIC - Software: 39 projetos
    * Finança: 14 projetos
    * TIC: 9 projetos
    * Outros: 4 projetos</code></pre>
</div>
</div>
</section>
<section id="análise-e-insights-da-pergunta-4" class="level3">
<h3 class="anchored" data-anchor-id="análise-e-insights-da-pergunta-4">Análise e Insights da Pergunta 4</h3>
<p><strong>O que foi investigado:</strong></p>
<p>Esta análise investigou a dispersão de trabalho dos analistas, medindo o número de áreas de conhecimento distintas que cada um avaliou. O objetivo era identificar se os analistas atuam como especialistas (focados em poucas áreas) ou como generalistas (atuando em múltiplas áreas), e compreender como essa distribuição pode afetar a qualidade das avaliações.</p>
<p><strong>Principais Descobertas:</strong></p>
<p>Os dados revelam um sistema com perfis heterogêneos de atuação, com importantes nuances a considerar:</p>
<ol type="1">
<li><strong>Distribuição da Dispersão:</strong>
<ul>
<li>O analista com maior diversificação, <strong>ID_301010505</strong>, atua em <strong>15 áreas distintas</strong> (562 projetos total)</li>
<li><strong>10 analistas</strong> trabalham com 8 ou mais áreas diferentes</li>
<li>A maioria dos analistas concentra-se em 2-5 áreas</li>
<li>O gráfico de dispersão mostra que não há correlação direta entre volume total e número de áreas</li>
</ul></li>
<li><strong>Padrão “Especialista com Cauda Longa”:</strong>
<ul>
<li>Mesmo analistas com alta dispersão mantêm áreas de concentração principal</li>
<li><strong>ID_301010505</strong>: 50.9% dos projetos em Software (286/562)</li>
<li><strong>ID_116768062</strong>: 41.8% em Metalurgia (145/347)</li>
<li><strong>ID_300603544</strong>: 39.3% em Software + 35.2% em TIC-Software (74.5% combinado)</li>
</ul></li>
<li><strong>Perfis de Especialização Identificados:</strong>
<ul>
<li><strong>Especialistas Digitais</strong>: Analistas focados em Software/TIC/Finança</li>
<li><strong>Especialistas Industriais</strong>: Concentrados em Metalurgia/Mecânica/Química</li>
<li><strong>Generalistas Controlados</strong>: Atuam em 6-8 áreas com distribuição mais equilibrada</li>
</ul></li>
</ol>
<p><strong>Insights e Implicações Práticas:</strong></p>
<ol type="1">
<li><p><strong>Flexibilidade Operacional</strong>: A dispersão observada pode refletir a necessidade de adaptação à demanda variável por área, permitindo melhor distribuição de carga de trabalho.</p></li>
<li><p><strong>Expertise Complementar</strong>: Analistas com formação multidisciplinar podem agregar valor em projetos que cruzam fronteiras tecnológicas, cada vez mais comuns em P&amp;D moderna.</p></li>
<li><p><strong>Oportunidades de Melhoria</strong>:</p>
<ul>
<li>Desenvolver matriz de competências para mapear expertise principal vs.&nbsp;secundária</li>
<li>Implementar sistema de alocação que considere tanto especialização quanto disponibilidade</li>
<li>Criar programa de capacitação cruzada para áreas emergentes</li>
</ul></li>
<li><p><strong>Equilíbrio Necessário</strong>: O modelo atual, com média de 4.6 áreas por analista, pode representar um ponto de equilíbrio entre especialização profunda e flexibilidade operacional.</p></li>
</ol>
<p><strong>Recomendações Construtivas:</strong></p>
<ul>
<li><strong>Mapeamento de Competências</strong>: Documentar formação e experiência dos analistas para alocação otimizada</li>
<li><strong>Mentoria Cruzada</strong>: Analistas especialistas podem orientar colegas em suas áreas secundárias</li>
<li><strong>Revisão Colaborativa</strong>: Para projetos em áreas secundárias, implementar revisão por especialista da área</li>
<li><strong>Formação Continuada</strong>: Investir em capacitação específica para analistas que demonstrem interesse em expandir expertise</li>
<li><strong>Indicadores de Qualidade</strong>: Monitorar se há diferença na qualidade das análises entre áreas primárias e secundárias</li>
<li><strong>Rotação Planejada</strong>: Permitir que analistas expandam gradualmente suas áreas de atuação com suporte adequado</li>
</ul>
</section>
</section>
<section id="pergunta-5-fichas-individuais-dos-top-15-analistas" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-5-fichas-individuais-dos-top-15-analistas">7. Pergunta 5: Fichas Individuais dos Top 15 Analistas</h2>
<p>Análise detalhada dos 15 analistas com maior volume de projetos</p>
<section id="pergunta-5" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-5">Pergunta 5</h3>
<div id="a849ed83" class="cell" data-execution_count="35">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Resumo dos Top 15 Analistas:
    analista_id  total_projetos  taxa_aprovacao_do  taxa_aprovacao_parecer  \
0     301040479             628               59.7                    64.5   
1     301010505             565               69.4                    41.4   
2     300713489             534               64.6                    24.2   
3     108293000             438               65.1                    50.5   
4     300603544             384               53.6                     4.7   
5     301241624             367               27.8                    24.5   
6     301043768             361               80.1                    78.7   
7     116768062             347               66.0                    59.4   
8     300788615             346               76.0                    45.4   
9     301064200             306               59.5                    32.4   
10    300869814             291               63.9                    48.1   
11    300850244             283               58.3                    56.2   
12    301043769             270               83.0                    77.4   
13    300869864             263               97.3                    93.2   
14    121916780             262               72.5                    48.1   

    taxa_concordancia  num_areas  
0                88.8          5  
1                58.9         15  
2                37.4          5  
3                77.5          3  
4                 8.7          8  
5                73.5          6  
6                97.6          5  
7                87.3          8  
8                58.6          3  
9                54.4          2  
10               74.2          3  
11               89.1          3  
12               87.9          5  
13               95.7          4  
14               65.3          8  </code></pre>
</div>
</div>
</section>
<section id="análise-e-insights-da-pergunta-5-com-base-na-imagem" class="level3">
<h3 class="anchored" data-anchor-id="análise-e-insights-da-pergunta-5-com-base-na-imagem">Análise e Insights da Pergunta 5 (com base na imagem)</h3>
<p><strong>O que foi investigado:</strong></p>
<p>As fichas de desempenho visual acima consolidam as métricas-chave (volume, taxas de aprovação, concordância e dispersão de áreas) para os 15 analistas com maior volume de projetos. O objetivo é transformar os dados em um perfil individualizado, facilitando a identificação de padrões e comportamentos atípicos (<em>outliers</em>).</p>
<p><strong>Principais Descobertas Visuais:</strong></p>
<p>A disposição em formato de “cards” torna a comparação entre os analistas imediata e intuitiva, destacando a heterogeneidade do grupo:</p>
<ul>
<li><p><strong>O Perfil Generalista:</strong> A ficha do analista <strong>ID 301010505</strong> (canto superior, centro) salta aos olhos pelo seu “Número de Áreas: 15”, o maior de todos. Este card visualiza claramente o perfil de um analista generalista, com uma taxa de concordância de apenas <strong>58.9%</strong>, sugerindo que a amplitude de sua atuação pode estar impactando o alinhamento de suas decisões.</p></li>
<li><p><strong>O Desalinhamento Crítico:</strong> O caso mais preocupante é visualizado na ficha do analista <strong>ID 300603544</strong> (segunda linha, centro). O número “Taxa Concordância: 8.7%” é um forte alerta visual. Ele indica que, apesar de analisar um grande volume de projetos (384), suas decisões de aprovação são quase sistematicamente revertidas pelo parecerista, apontando para um desalinhamento fundamental de critérios.</p></li>
<li><p><strong>O Benchmark de Consistência:</strong> Em forte contraste, a ficha do analista <strong>ID 300869864</strong> (penúltima linha, centro) funciona como um modelo de referência. Os valores de “Taxa Aprovação DO: 97.3%” e “Taxa Concordância: 95.7%” mostram um alinhamento quase perfeito, representando um padrão de alta produtividade e consistência com a fase de parecer.</p></li>
<li><p><strong>O Perfil Rigoroso:</strong> A ficha do <strong>ID 301241624</strong> (segunda linha, à esquerda) ilustra o perfil do analista mais rigoroso, com uma “Taxa Aprovação DO” de apenas <strong>27.8%</strong>. A visualização conjunta com a “Taxa Concordância” de <strong>73.5%</strong> permite inferir que, embora aprove poucos projetos, suas recomendações são, em geral, bem fundamentadas e mantidas.</p></li>
</ul>
<p><strong>Insights e Implicações Práticas:</strong></p>
<p>A visualização em formato de ‘ficha’ transforma uma tabela de dados em uma ferramenta de gestão de desempenho muito mais eficaz. Para um gestor, é possível identificar com um rápido olhar os perfis que necessitam de atenção, como os que apresentam baixa concordância ou dispersão excessiva de áreas. Da mesma forma, os perfis de alta consistência podem ser estudados para disseminar boas práticas. Esta abordagem visual é fundamental para iniciar diálogos focados, calibrar critérios e otimizar o processo de avaliação de forma mais ágil e intuitiva.</p>
</section>
</section>
<section id="pergunta-6-modelo-preditivo-de-aprovação-no-parecer" class="level2">
<h2 class="anchored" data-anchor-id="pergunta-6-modelo-preditivo-de-aprovação-no-parecer">8. Pergunta 6: Modelo Preditivo de Aprovação no Parecer</h2>
<p>Análise complexa: probabilidade de aprovação baseada em características do projeto e analista</p>
<section id="pergunta-6---preparação-dos-dados" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-6---preparação-dos-dados">Pergunta 6 - Preparação dos dados</h3>
<div id="36b10ac1" class="cell" data-execution_count="36">
<div class="cell-output cell-output-stdout">
<pre><code>Preparando dados para o modelo preditivo...
Projetos válidos para modelagem: 13,196</code></pre>
</div>
</div>
</section>
<section id="pergunta-6---feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-6---feature-engineering">Pergunta 6 - Feature Engineering</h3>
<div id="9d52d1d3" class="cell" data-execution_count="37">
<div class="cell-output cell-output-stdout">
<pre><code>Criando features TF-IDF...
Criando features categóricas...
Shape das features: (13196, 104)
Distribuição do target: aprovado_parecer
0    0.553956
1    0.446044
Name: proportion, dtype: float64</code></pre>
</div>
</div>
</section>
<section id="pergunta-6---treinamento-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-6---treinamento-do-modelo">Pergunta 6 - Treinamento do modelo</h3>
<div id="2770c51a" class="cell" data-execution_count="38">
<div class="cell-output cell-output-stdout">
<pre><code>
Treinando modelo Random Forest...

Performance do Modelo:
              precision    recall  f1-score   support

           0       0.85      0.77      0.81      1462
           1       0.75      0.83      0.79      1178

    accuracy                           0.80      2640
   macro avg       0.80      0.80      0.80      2640
weighted avg       0.81      0.80      0.80      2640


ROC-AUC médio (cross-validation): 0.831 (+/- 0.021)</code></pre>
</div>
</div>
</section>
<section id="pergunta-6---análise-de-importância-das-features" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-6---análise-de-importância-das-features">Pergunta 6 - Análise de importância das features</h3>
<div id="ed1776a3" class="cell" data-execution_count="39">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="analise_analistas_parecerista_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Top 10 Palavras/Bigramas Mais Importantes:
- plataforma: 0.0401
- integração: 0.0369
- dados: 0.0292
- de dados: 0.0275
- em: 0.0242
- informações: 0.0235
- 2021: 0.0176
- de: 0.0152
- processos: 0.0109
- as: 0.0106</code></pre>
</div>
</div>
</section>
<section id="pergunta-6---análise-de-cenários" class="level3">
<h3 class="anchored" data-anchor-id="pergunta-6---análise-de-cenários">Pergunta 6 - Análise de cenários</h3>
<div id="3a9ee659" class="cell" data-execution_count="40">
<div class="cell-output cell-output-stdout">
<pre><code>
================================================================================
ANÁLISE DE CENÁRIOS - Probabilidade de Aprovação no Parecer
================================================================================

Cenário 1 - Perfil de Alta Aprovação:
  Área: Outros
  Analista: ID_301040479
  Palavras-chave técnicas: plataforma integração dados de dados em
  Número de palavras-chave: 5
  → Probabilidade de Aprovação: 32.6%

Cenário 2 - Perfil de Baixa Aprovação:
  Área: Software
  Analista: ID_300713489
  Palavras-chave técnicas: projeto simples básico
  Número de palavras-chave: 1
  → Probabilidade de Aprovação: 12.8%

Cenário 3 - Mesmo Projeto, Diferentes Analistas:
  Área: Outros
  Palavras: plataforma integração dados de dados em
  Número de palavras-chave: 5
  - Analista ID_301040479 (taxa histórica: 59.7%): 32.6%
  - Analista ID_301010505 (taxa histórica: 69.4%): 34.8%
  - Analista ID_300713489 (taxa histórica: 64.6%): 31.1%
  - Analista ID_108293000 (taxa histórica: 65.1%): 32.0%
  - Analista ID_300603544 (taxa histórica: 53.6%): 23.7%</code></pre>
</div>
</div>
</section>
</section>
<section id="análise-e-insights-da-pergunta-6-modelo-preditivo-de-aprovação-no-parecer" class="level2">
<h2 class="anchored" data-anchor-id="análise-e-insights-da-pergunta-6-modelo-preditivo-de-aprovação-no-parecer">Análise e Insights da Pergunta 6: Modelo Preditivo de Aprovação no Parecer</h2>
<section id="o-que-foi-investigado" class="level3">
<h3 class="anchored" data-anchor-id="o-que-foi-investigado">O que foi investigado:</h3>
<p>Foi desenvolvido um modelo de Machine Learning (Random Forest) para prever a probabilidade de aprovação de projetos na fase de Parecer, utilizando características textuais (TF-IDF), informações estruturais (área, analista) e métricas históricas. O modelo busca identificar quais fatores mais influenciam a decisão final e quantificar o impacto de diferentes variáveis na probabilidade de aprovação.</p>
</section>
<section id="principais-descobertas-visuais" class="level3">
<h3 class="anchored" data-anchor-id="principais-descobertas-visuais">Principais Descobertas Visuais:</h3>
<section id="hierarquia-de-importância-das-features-gráfico-à-esquerda" class="level4">
<h4 class="anchored" data-anchor-id="hierarquia-de-importância-das-features-gráfico-à-esquerda">1. <strong>Hierarquia de Importância das Features (Gráfico à esquerda):</strong></h4>
<p>O gráfico de barras horizontais revela uma hierarquia clara de influência: - <strong>Taxa histórica do analista</strong> domina com 49.7% da importância relativa, confirmando que o comportamento histórico é o preditor mais forte - <strong>Área do projeto</strong> contribui com 38.8%, indicando forte especialização setorial nas decisões - <strong>Características textuais</strong> (termos TF-IDF) ocupam as posições seguintes, com destaque para “plataforma” (0.0401), “integração” (0.0369) e “dados” (0.0292)</p>
</section>
<section id="distribuição-de-importância-das-features-estruturais-gráfico-à-direita" class="level4">
<h4 class="anchored" data-anchor-id="distribuição-de-importância-das-features-estruturais-gráfico-à-direita">2. <strong>Distribuição de Importância das Features Estruturais (Gráfico à direita):</strong></h4>
<p>O gráfico de pizza decompõe a importância relativa das 4 features não-textuais: - <strong>Taxa histórica do analista</strong>: 49.7% - O fator individual mais determinante - <strong>Área encoded</strong>: 38.8% - Segundo fator mais importante, refletindo especialização setorial - <strong>Analista encoded</strong>: 9.2% - Efeito individual do analista além de sua taxa histórica - <strong>Número de palavras-chave</strong>: 2.3% - Impacto marginal da quantidade de keywords</p>
</section>
</section>
<section id="métricas-de-performance-do-modelo" class="level3">
<h3 class="anchored" data-anchor-id="métricas-de-performance-do-modelo">Métricas de Performance do Modelo:</h3>
<ul>
<li><strong>ROC-AUC</strong>: 0.831 (±0.021) - Excelente capacidade discriminativa</li>
<li><strong>Acurácia</strong>: 80% - 4 em cada 5 previsões corretas</li>
<li><strong>Recall classe positiva</strong>: 83% - Alta sensibilidade para projetos aprovados</li>
<li><strong>Precision classe negativa</strong>: 85% - Alta especificidade para projetos reprovados</li>
</ul>
</section>
<section id="análise-do-vocabulário-preditivo" class="level3">
<h3 class="anchored" data-anchor-id="análise-do-vocabulário-preditivo">Análise do Vocabulário Preditivo:</h3>
<p>Os termos mais importantes revelam padrões linguísticos associados ao sucesso: 1. <strong>“plataforma”</strong> (0.0401) - Sugere soluções tecnológicas integradas 2. <strong>“integração”</strong> (0.0369) - Indica complexidade e valor agregado 3. <strong>“dados”</strong> (0.0292) - Reflete foco em transformação digital 4. <strong>“informações”</strong> (0.0235) - Complementa o tema de gestão de dados 5. <strong>“2021”</strong> (0.0176) - Possível indicador de projetos recentes/atualizados</p>
</section>
<section id="análise-de-cenários-preditivos" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-cenários-preditivos">Análise de Cenários Preditivos:</h3>
<section id="cenário-1---perfil-teoricamente-favorável" class="level4">
<h4 class="anchored" data-anchor-id="cenário-1---perfil-teoricamente-favorável"><strong>Cenário 1 - Perfil Teoricamente Favorável:</strong></h4>
<ul>
<li>Área: “Outros” + Analista top performer + Vocabulário otimizado</li>
<li><strong>Resultado surpreendente</strong>: Apenas 32.6% de probabilidade</li>
<li><strong>Insight</strong>: Mesmo com condições “ideais”, o modelo é conservador, sugerindo que fatores não capturados têm peso significativo</li>
</ul>
</section>
<section id="cenário-2---perfil-desfavorável" class="level4">
<h4 class="anchored" data-anchor-id="cenário-2---perfil-desfavorável"><strong>Cenário 2 - Perfil Desfavorável:</strong></h4>
<ul>
<li>Área: “Software” + Analista com histórico misto + Texto genérico</li>
<li><strong>Resultado</strong>: 12.8% de probabilidade</li>
<li><strong>Insight</strong>: Confirma penalização forte para projetos com descrições vagas</li>
</ul>
</section>
<section id="cenário-3---variação-por-analista" class="level4">
<h4 class="anchored" data-anchor-id="cenário-3---variação-por-analista"><strong>Cenário 3 - Variação por Analista:</strong></h4>
<ul>
<li>Mesmo projeto testado com 5 analistas diferentes</li>
<li><strong>Variação</strong>: 23.7% a 34.8% (amplitude de 11.1 pontos percentuais)</li>
<li><strong>Insight crítico</strong>: A identidade do analista pode alterar a probabilidade em até 46% (de 23.7% para 34.8%)</li>
</ul>
</section>
</section>
<section id="implicações-práticas-e-recomendações" class="level3">
<h3 class="anchored" data-anchor-id="implicações-práticas-e-recomendações">Implicações Práticas e Recomendações:</h3>
<section id="para-gestores-do-programa" class="level4">
<h4 class="anchored" data-anchor-id="para-gestores-do-programa"><strong>1. Para Gestores do Programa:</strong></h4>
<ul>
<li><strong>Sistema de Apoio à Decisão</strong>: Implementar o modelo como ferramenta de triagem prévia</li>
<li><strong>Calibração de Analistas</strong>: Usar as previsões para identificar e corrigir vieses individuais</li>
<li><strong>Alocação Inteligente</strong>: Direcionar projetos para analistas com perfil adequado</li>
</ul>
</section>
<section id="para-empresas-proponentes" class="level4">
<h4 class="anchored" data-anchor-id="para-empresas-proponentes"><strong>2. Para Empresas Proponentes:</strong></h4>
<ul>
<li><strong>Otimização Textual</strong>: Incorporar vocabulário técnico específico (“plataforma”, “integração”, “dados”)</li>
<li><strong>Seleção de Área</strong>: Considerar o impacto da classificação setorial na probabilidade</li>
<li><strong>Detalhamento Técnico</strong>: Evitar descrições genéricas; quanto mais específico, melhor</li>
</ul>
</section>
<section id="para-melhoria-do-modelo" class="level4">
<h4 class="anchored" data-anchor-id="para-melhoria-do-modelo"><strong>3. Para Melhoria do Modelo:</strong></h4>
<ul>
<li><strong>Features Adicionais</strong>: Incorporar métricas financeiras, histórico da empresa, complexidade técnica</li>
<li><strong>Ensemble Methods</strong>: Combinar com outros algoritmos para aumentar robustez</li>
<li><strong>Análise Temporal</strong>: Incluir tendências e sazonalidades nas aprovações</li>
</ul>
</section>
</section>
<section id="limitações-e-considerações" class="level3">
<h3 class="anchored" data-anchor-id="limitações-e-considerações">Limitações e Considerações:</h3>
<ol type="1">
<li><strong>Probabilidades Conservadoras</strong>: Mesmo cenários favoráveis resultam em probabilidades &lt;35%, sugerindo:
<ul>
<li>Desequilíbrio nos dados de treino</li>
<li>Fatores ocultos não capturados</li>
<li>Necessidade de recalibração do modelo</li>
</ul></li>
<li><strong>Dependência do Analista</strong>: A taxa histórica domina com ~50% da importância, indicando:
<ul>
<li>Risco de perpetuar vieses existentes</li>
<li>Necessidade de estratégias de “debiasing”</li>
<li>Oportunidade para padronização de critérios</li>
</ul></li>
<li><strong>Vocabulário Dominante</strong>: Termos genéricos (“dados”, “em”, “de”) no top 10 sugerem:
<ul>
<li>Necessidade de pré-processamento mais sofisticado</li>
<li>Potencial para n-gramas de ordem superior</li>
<li>Análise semântica além de frequência</li>
</ul></li>
</ol>
</section>
<section id="conclusão" class="level3">
<h3 class="anchored" data-anchor-id="conclusão">Conclusão:</h3>
<p>O modelo demonstra viabilidade técnica robusta (ROC-AUC 0.831) para predição automatizada, mas revela dependência preocupante de fatores históricos e individuais. A dominância da “taxa histórica do analista” (49.7%) sobre características intrínsecas do projeto sugere que o sistema atual pode estar perpetuando padrões passados em vez de avaliar objetivamente o mérito técnico. A implementação prática deve focar em usar o modelo como ferramenta de apoio e alerta, não substituição da análise humana, priorizando a identificação e correção de vieses sistêmicos.</p>
</section>
</section>
<section id="conclusões-e-insights-principais" class="level2">
<h2 class="anchored" data-anchor-id="conclusões-e-insights-principais">9. Conclusões e Insights Principais</h2>
<div id="fc6cecdb" class="cell" data-execution_count="41">
<div class="cell-output cell-output-stdout">
<pre><code>
================================================================================
PRINCIPAIS CONCLUSÕES DA ANÁLISE
================================================================================

1. TAXA DE APROVAÇÃO POR ANALISTA:
   - Taxa média de aprovação (DO): 62.0%
   - Variação: 0.0% a 100.0%
   - Desvio padrão: 27.1%

2. CONCORDÂNCIA DO → PARECER:
   - Taxa média de concordância: 66.9%
   - Analistas com concordância &lt; 50%: 19

3. REVERSÕES DE DECISÃO:
   - Taxa média de reversão (Não Recom → Recom): 4.8%
   - Áreas com maior reversão: Mecânica, Transporte, Construção Civil

4. DISPERSÃO DE ÁREAS:
   - Média de áreas por analista: 4.6
   - Máximo de áreas atendidas: 15
   - Analistas com &gt;10 áreas: 1

5. MODELO PREDITIVO:
   - Acurácia do modelo: 80.0%
   - ROC-AUC: 0.831
   - Features mais importantes: Taxa histórica do analista, Área do projeto, Palavras técnicas

6. RECOMENDAÇÕES:
   - Implementar especialização por área para reduzir dispersão
   - Revisar critérios de avaliação para aumentar concordância DO-Parecer
   - Investigar áreas com alta taxa de reversão para padronizar critérios
   - Considerar balanceamento de carga entre analistas

✅ Resultados salvos em 'analise_analistas_parecerista_resultados.xlsx'
✅ Análise concluída!</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>